version: "3.8"

services:
    react-app:
        build:
            context: ./react-app
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        environment:
            - NODE_ENV=production
        restart: always

    nodejs-app:
        build:
            context: ./nodejs-app
            dockerfile: Dockerfile
        ports:
            - "4000:4000"
        environment:
            - NODE_ENV=production
        restart: always

    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - react-app
            - nodejs-app
        restart: always
