services:
    frontend:
        image: pellevkv/vkvrestauraties:latest
        container_name: vkvrestauraties_frontend
        ports:
            - "8000:3000" # Maps localhost:8000 to the container's port 3000
        depends_on:
            - backend
        networks:
            - vkv_network

    backend:
        image: pellevkv/vkvrestauraties_backend:latest
        container_name: vkvrestauraties_backend
        ports:
            - "8080:8080" # Maps localhost:8080 to the container's port 8080
        networks:
            - vkv_network

networks:
    vkv_network:
        driver: bridge
